### PR TITLE
Converted XAE project to PLC project

### PR DESCRIPTION
**Pull request by koder29406**
Converted OSCAT solution from full XAE project, it's not necessary for compiling libraries. The System Manager and IO is for connecting to hardware, and it's faster working without them.

### CODE REVIEW

**Comment by katharinabr** [comment]
This is part of #49 .

**Comment by StGoebel** [comment]
Thanks for contributing to AixOCAT @koder29406. 
Please follow the git workflow and create an issue for future contribution.

**Comment by koder29406** [comment]
I can remove the gitignore changes, and just leave the project converting. Does that sound ok?

**Comment by StGoebel** [comment]
sounds good!

**Pull request merged**
